services:
  - type: web
    name: smartinvoice-ia1
    runtime: docker
    rootDir: practica3
    dockerfilePath: ./Dockerfile.cloud
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartinvoice-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false

databases:
  - name: smartinvoice-db
    databaseName: smartinvoice
    user: smartinvoice
